# This file holds config that changes for each performed release
# eksbuild can be used to perform an arbitrary version bump when
# the build process or patches change but the underlying version
# does not change (e.g. to patch a CVE early before upstream)

csi-attacher:
  tag: 'v4.11.0'
  eksbuild: '1'
csi-node-driver-registrar:
  tag: 'v2.16.0'
  eksbuild: '1'
csi-provisioner:
  tag: 'v6.1.1'
  eksbuild: '1'
csi-resizer:
  tag: 'v2.1.0'
  eksbuild: '1'
csi-snapshotter:
  tag: 'v8.5.0'
  eksbuild: '1'
livenessprobe:
  tag: 'v2.18.0'
  eksbuild: '1'
snapshot-controller:
  tag: 'v8.5.0'
  eksbuild: '1'
