# This file holds config that changes for each performed release
# eksbuild can be used to perform an arbitrary version bump when
# the build process or patches change but the underlying version
# does not change (e.g. to patch a CVE early before upstream)

csi-attacher:
  tag: 'v4.10.0'
  eksbuild: '2'
csi-node-driver-registrar:
  tag: 'v2.15.0'
  eksbuild: '2'
csi-provisioner:
  tag: 'v6.1.0'
  eksbuild: '1'
csi-resizer:
  tag: 'v2.0.0'
  eksbuild: '1'
csi-snapshotter:
  tag: 'v8.4.0'
  eksbuild: '2'
livenessprobe:
  tag: 'v2.17.0'
  eksbuild: '2'
snapshot-controller:
  tag: 'v8.4.0'
  eksbuild: '2'
